import Head from 'next/head'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'

import { KVideo } from './components'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  const kalturaVideoSource = [
    {
      title: "Video 01",
      video: `<div>
      <script src="https://cdnapisec.kaltura.com/p/811441/sp/81144100/embedIframeJs/uiconf_id/41588491/partner_id/811441"></script>
      <div id="kaltura_player_1527160978" style="width: 500px; height: 350px;"></div>
      <script>
          kWidget.thumbEmbed({
              "targetId": "kaltura_player_1527160978",
              "wid": "_811441",
              "uiconf_id": 41588491,
              "flashvars": {},
              "cache_st": "1527160978",
              "entry_id": "0_cm8rhiwp"
          });
      </script>
      </div>`
    },
    {
      title: "Video 02",
      video: `<div>
      <script src="https://cdnapisec.kaltura.com/p/811441/sp/81144100/embedIframeJs/uiconf_id/41588491/partner_id/811441"></script>
      <div id="kaltura_player_15271609789" style="width: 500px; height: 350px;"></div>
      <script>
          kWidget.thumbEmbed({
              "targetId": "kaltura_player_15271609789",
              "wid": "_811441",
              "uiconf_id": 41588491,
              "flashvars": {},
              "cache_st": "15271609789",
              "entry_id": "0_cm8rhiwp"
          });
      </script>
      </div>`
    }
  ]

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main} ${inter.className}`}>
        <div className={styles.grid}>
          {kalturaVideoSource.map((v: any, i: number) => (
            <div key={i} className={styles.card}>
              <h2>{v.title}</h2>
              <p>Sample Kaltura video</p>
              <KVideo videoData={v.video} />
            </div>
          ))}
        </div>
      </main>
    </>
  )
}
